#!/usr/bin/env python3
"""Regenerate page.h from index.html and seed.json.

Run after editing either file, then recompile. Every non-ASCII byte is written
as an octal escape, so page.h compiles identically under any Windows code page.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
PART_LIMIT = 12000  # raw bytes per string; keeps MSVC well under its literal limits


def literal(data: bytes) -> str:
    lines, cur = [], []
    for b in data:
        if b == 0x0A:
            cur.append("\\n")
            lines.append('"' + "".join(cur) + '"')
            cur = []
        elif b in (0x22, 0x5C):
            cur.append("\\" + chr(b))
        elif b == 0x3F:  # avoid trigraphs
            cur.append("\\?")
        elif 0x20 <= b < 0x7F:
            cur.append(chr(b))
        else:
            cur.append("\\%03o" % b)
    if cur or not lines:
        lines.append('"' + "".join(cur) + '"')
    return "\n    ".join(lines)


def split_parts(data: bytes):
    parts, start = [], 0
    while start < len(data):
        end = min(start + PART_LIMIT, len(data))
        if end < len(data):
            nl = data.rfind(b"\n", start, end)
            if nl > start:
                end = nl + 1
        parts.append(data[start:end])
        start = end
    return parts


def parts_array(name: str, data: bytes) -> str:
    body = "".join("    " + literal(part) + ",\n" for part in split_parts(data))
    return "static const char *const %s[] = {\n%s    0\n};\n\n" % (name, body)


def db_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r")


def main():
    html = (HERE / "index.html").read_bytes()
    seed = json.loads((HERE / "seed.json").read_text(encoding="utf-8"))
    seed_db = "".join(
        "%d\t%s\t%s\t%s\t%s\t0\n"
        % (i, db_escape(r["category"]), db_escape(r["title"]), db_escape(r["code"]), db_escape(r.get("note", "")))
        for i, r in enumerate(seed, 1)
    )
    seed_json = json.dumps(
        [{k: r.get(k, "") for k in ("category", "title", "code", "note")} for r in seed],
        ensure_ascii=False, indent=0,
    )
    out = ["/* Generated by gen_page.py from index.html and seed.json - do not edit by hand. */\n"]
    out.append(parts_array("PAGE_PARTS", html))
    out.append(parts_array("SEED_DB_PARTS", seed_db.encode("utf-8")))
    out.append(parts_array("SEED_JSON_PARTS", seed_json.encode("utf-8")))
    (HERE / "page.h").write_text("".join(out), encoding="ascii", newline="\n")
    print("page.h: %d bytes of HTML, %d seed records" % (len(html), len(seed)))


if __name__ == "__main__":
    main()
